---
# configuration file for experiment 
# paths to directories
dataset: tum
dataset_seq_path: ../datasets/rgbd_dataset_freiburg1_desk/
output_path: ../results/config_5/
pose_path: ../datasets/rgbd_dataset_freiburg1_desk/pose_per_frame/
trained_models_path: ../trained-models/UfM_FCDenseNet_Ensemble
trained_model_folder: nyudepthv2.modality=rgb.arch=FCDenseNet.criterion=heteroscedastic.lr=0.001.adjustlr=1.optimizer=SGD.bs=4.pretrained=False.epochs=50.dropoutP=0.bootstrap=False.ensemble= # without ensemble member number, added in utils
best_model_name: checkpoint-50.pth.tar
# mode 
method: 
- aleatoric
- ensemble
- ensemble_UfM
- aleatoric_UfM
- full_ensemble_UfM
# - MCDropout # needs p > 0
# - MCDropout_UfM # needs p > 0
# - full_MCDropout_UfM # needs p > 0
evaluate: True
loss: heteroscedastic
ensemble_size: 10
p: 0 # dropout probability 
num_inferences: 1 
input_height: 224
input_width: 224 
# TUM Freiburg 1 camera calibration
fx: 181.055 # 517.3/640*224
fy: 241.03333334 #  516.5/480*224
cx: 111.51 # 318.6/640*224
cy: 119.14 # 255.3/480*224
max_cloud_size: 100000
# hardware parameters
device: GPU
num_cores: 1
workers: 10
# printing/saving parameters
print_freq: 100
store_freq: 100
max_frames_to_save: 10000000000000000 # no max 