---
# configuration file for experiment 
# paths to directories
dataset: tum
dataset_seq_path: ../datasets/rgbd_dataset_freiburg3_long_office_household/
output_path: ../results/config_4/
pose_path: ../datasets/rgbd_dataset_freiburg3_long_office_household/pose_per_frame/
trained_models_path: ../trained-models/UfM_FCDenseNet_Ensemble
trained_model_folder: nyudepthv2.modality=rgb.arch=FCDenseNet.criterion=heteroscedastic.lr=0.001.adjustlr=1.optimizer=SGD.bs=4.pretrained=False.epochs=50.dropoutP=0.bootstrap=False.ensemble= # without ensemble member number, added in utils
best_model_name: checkpoint-50.pth.tar
# mode 
method: 
# - aleatoric
# - ensemble
# - ensemble_UfM
# - aleatoric_UfM
# - full_ensemble_UfM
- MCDropout # needs p > 0
- MCDropout_UfM # needs p > 0
- full_MCDropout_UfM # needs p > 0
evaluate: True
loss: heteroscedastic
ensemble_size: 10
p: 0.05 # dropout probability 
num_inferences: 10 # only used for MCDropout and full_MCDropout_UfM, other methods will default to 1
input_height: 224
input_width: 224 
# TUM Freiburg 3 camera calibration
fx: 187.39 # 535.4/640*224
fy: 251.626667 # 539.2/480*224
cx: 112.035 # 320.1/640*224
cy: 115.546667 # 247.6/480*224
max_cloud_size: 100000
# hardware parameters
device: GPU
num_cores: 1
workers: 10
# printing/saving parameters
print_freq: 100
store_freq: 100
max_frames_to_save: 10000000000000000 # no max 